apiVersion: v1 
kind: Pod
metadata:
  name: redis-pod
  labels:
    name: redis-pod
    app: voting-app-pod
spec:
  containers:
    - name: redis-pod
      image: redis
      ports:
        - containerPort: 6379