apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-dep
  labels:
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-voting-app
  template:
    metadata:
      name: redis-pod
      labels:
        app: demo-voting-app
    spec:
      containers:
        - name: redis-pod
          image: redis
          ports:
            - containerPort: 6379
    