apiVersion: v1 
kind: Pod
metadata:
  name: result-app-pod
  labels:
    name: result-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: result-app
      image: diya0311/result:v1
      ports:
        - containerPort: 80