apiVersion: v1
kind: Deployment
metadata:
  name: result-app-dep
  labels:
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-voting-app
  template:
    metadata:
      name: result-app-pod
      labels:
        app: demo-voting-app
    spec:
      containers:
        - name: result-app
          image: diya0311/result:v1
          ports:
            - containerPort: 80
        