apiVersion: v1 
kind: Service
metadata:
  name: db
  labels:
    app: demo-voting-app
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: demo-voting-app
---
apiVersion: v1 
kind: Service
metadata:
  name: redis
  labels:
    app: demo-voting-app
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: demo-voting-app

---
apiVersion: v1 
kind: Service
metadata:
  name: result-service 
  labels:
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector:
    app: demo-voting-app

---
apiVersion: v1 
kind: Service
metadata:
  name: voting-service 
  labels:
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  selector:
    app: demo-voting-app
