apiVersion: v1 
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: workeer-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: worker-app
      image: diyakashyap/examplevotingapp_worker:v1